name: Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      bucket:
        description: "The S3 bucket name."
        required: true
      bucket-region:
        description: "The region of the s3 bucket."
        required: false
        default: "us-east-1"
      dist-folder:
        description: "The folder containing the files to be deployed."
        required: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
      - name: Output information
        run: |
          echo "Cache used: ${{ steps.cache-deps.outputs.used-cache }}"
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        with:
          caching: "false"
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        uses: ./.github/actions/deploy-s3-javascript
        with:
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: us-east-1
          dist-folder: ./dist

  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Run Custom Action
        uses: ./.github/actions/deploy-s3-javascript
        with:
          bucket: ${{ github.event.inputs.bucket }}
          bucket-region: ${{ github.event.inputs.bucket-region }}
          dist-folder: ${{ github.event.inputs.dist-folder }}
